Conformer averaging model support for pytorch 1.6
Averaging int tensors in Pytorch 1.6 gives a run time error - 

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

This PR will look for integer tensors and average accordingly.